// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1SEXVfpriwQCgBsaIFn7iObPVULsYOI',
    appId: '1:769350708822:web:a9389d078eb9ba9cea55f7',
    messagingSenderId: '769350708822',
    projectId: 'task-management-apps-2c73e',
    authDomain: 'task-management-apps-2c73e.firebaseapp.com',
    storageBucket: 'task-management-apps-2c73e.appspot.com',
    measurementId: 'G-Z5GF096QTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQl16dsgcWvxL4GFe8_7zvCZEQLWODTs',
    appId: '1:769350708822:android:74a6a3b284126a39ea55f7',
    messagingSenderId: '769350708822',
    projectId: 'task-management-apps-2c73e',
    storageBucket: 'task-management-apps-2c73e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2FEUZPr1TmRFSxrjECToGwDUR59In-s',
    appId: '1:769350708822:ios:6fd757a3e25991e0ea55f7',
    messagingSenderId: '769350708822',
    projectId: 'task-management-apps-2c73e',
    storageBucket: 'task-management-apps-2c73e.appspot.com',
    androidClientId: '769350708822-pm8jphit3hv4mk31rh2k0ekj1q620qv8.apps.googleusercontent.com',
    iosClientId: '769350708822-0aovmaghbhe40inj1q69744gqfgpvoeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPertama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf2FEUZPr1TmRFSxrjECToGwDUR59In-s',
    appId: '1:769350708822:ios:6fd757a3e25991e0ea55f7',
    messagingSenderId: '769350708822',
    projectId: 'task-management-apps-2c73e',
    storageBucket: 'task-management-apps-2c73e.appspot.com',
    androidClientId: '769350708822-pm8jphit3hv4mk31rh2k0ekj1q620qv8.apps.googleusercontent.com',
    iosClientId: '769350708822-0aovmaghbhe40inj1q69744gqfgpvoeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPertama',
  );
}
